AllCops:
  RunRailsCops: false
  DisplayCopsNames: true
  StyleGuideCopsOnly: false

Style/Documentation:
  Enabled: false

Style/EndOfLine:
  Enabled: false

Style/UnneededPercentQ:
  Enabled: false

Metrics/LineLength:
  Max: 120
